14OI:
  scientific_name: "Merops apiaster"
  tag_create:
    crop_start: "2015-08-09"
    crop_end: "2016-07-11"
  tag_set_map: # ?tag_set_map()
    extent: [-5, 25, -10, 55] # [W, E, S, N]
    scale: 5
    known:
      stap_id: [1, 2, 3] # -1 -> last stap
      start: ["2015-08-09 00:00", "2015-10-04 12:00", "2016-05-20 12:00"]
      end: ["2015-08-31 12:00", "2016-03-30 12:00", "2016-07-11 00:00"]
      known_lon: [11.93128, null, 11.93128]
      known_lat: [51.3629, null, 51.3629]

12GE:
  scientific_name: "Tachymarptis melba"
  tag_create:
    crop_start: "2014-07-04"
    crop_end: "2015-06-10"
  tag_set_map:
    extent: [5, 50, -10, 50]
    scale: 2
    known:
      stap_id: [1, 2, 3, 4]
      start:
        [
          "2014-07-04 00:00",
          "2014-10-06 12:00",
          "2014-12-04 12:00",
          "2015-04-07 12:00",
        ]
      end:
        [
          "2014-10-1 12:00",
          "2014-11-30 12:00",
          "2015-03-30 12:00",
          "2015-06-10 00:00",
        ]
      known_lon: [23.4, null, null, 23.4]
      known_lat: [42.7, null, null, 42.7]
